In [1]:
import numpy as np

In [2]:
a = [1, 2, 3]
b = [4, 5, 6]

In [8]:
c = np.array([a, b], float)

In [9]:
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
np.shape(c)

(2, 3)

In [15]:
2 in a

True

In [16]:
2.0 in c

True

In [17]:
c.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [18]:
s = c.tostring()

In [19]:
s


b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@\x00\x00\x00\x00\x00\x00\x10@\x00\x00\x00\x00\x00\x00\x14@\x00\x00\x00\x00\x00\x00\x18@'

In [21]:
x = np.frombuffer(s)

In [23]:
print(x)

[1. 2. 3. 4. 5. 6.]
